name: flutter_application_time_checker
description: "A cross-platform application for saving timings. Builds graphs, helps to track the dynamics of progress."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0
  json_annotation: ^4.9.0
  sqflite_common_ffi: ^2.3.4+4
  fl_chart: ^0.71.0
  async: ^2.13.0
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Berlin
      fonts:
        - asset: assets/fonts/Berlin-j9029.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Var.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Var.ttf

